services:
  devTemplate:
    build:
      context: ..
      dockerfile: docker/app.Dockerfile
    container_name: devTemplate
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - NODE_ENV=production
      - PORT=3000
      # Externer Postgres direkt per URL (Sonderzeichen im PW URL-encoden!)
      - DATABASE_URL=postgresql://POSTGRES_USER:POSTGRES_PASS_ENCODED@POSTGRES_IP:POSTGRES_PORT/POSTGRES_DB
    ports:
      - "8080:3000"
    volumes:
      - /mnt/user/appdata/devTemplate/.next/cache:/app/.next/cache
